# Config for https://github.com/apps/release-drafter
name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'Dependency Updates'
    label: 'dependencies'
template: |
  ## Changes

  $CHANGES

  ## Upgrading

  To upgrade, update your `pipeline.yml` files:

  ```diff
  steps:
    - command: test.sh
      plugins:
  -     docker-compose#$PREVIOUS_TAG:
  +     docker-compose#v$NEXT_MINOR_VERSION:
          image: someimage
          workdir: /app
  ```
